//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_Invoice
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Shipment_Number { get; set; }
        public Nullable<int> SO_Number { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Billing_Address { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Billing_City { get; set; }
        public string Billing_State { get; set; }
        public int Billing_Country_Id { get; set; }
        public string Billing_ZipCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Sales_Order Sales_Order { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
