//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AR_Invoice = new HashSet<AR_Invoice>();
            this.Quotes = new HashSet<Quote>();
            this.Shipments = new HashSet<Shipment>();
            this.Sales_Order = new HashSet<Sales_Order>();
        }
    
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Description { get; set; }
        public string Billing_Address { get; set; }
        public string Shipping_Address { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<decimal> Credit_Limit { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Email { get; set; }
        public int Sales_Person_Id { get; set; }
        public Nullable<int> Billing_Country_Id { get; set; }
        public Nullable<int> Shipping_Country_Id { get; set; }
        public string Billing_City { get; set; }
        public string Shipping_City { get; set; }
        public string Billing_State { get; set; }
        public string Shipping_State { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Shipping_ZipCode { get; set; }
        public string Billing_ZipCode { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AR_Invoice> AR_Invoice { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order> Sales_Order { get; set; }
        public virtual Sales_Person Sales_Person { get; set; }
        public virtual Tax Tax1 { get; set; }
    }
}
