//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<double> Hourly_Rate { get; set; }
        public int Dept_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
