//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Quote_Items = new HashSet<Quote_Items>();
            this.SO_Items = new HashSet<SO_Items>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Rev { get; set; }
        public int Group_Id { get; set; }
        public int Product_Class_Id { get; set; }
        public int Warehouse_Id { get; set; }
        public int Bin_Id { get; set; }
        public Nullable<int> Type { get; set; }
        public int UOM_Id { get; set; }
    
        public virtual Bin Bin { get; set; }
        public virtual Group Group { get; set; }
        public virtual Product_Class Product_Class { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_Items> Quote_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_Items> SO_Items { get; set; }
    }
}
