//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Class()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string Sales { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public int GL_Account { get; set; }
        public int Id { get; set; }
    
        public virtual GL_Account GL_Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
    }
}
