//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.Sales_Order = new HashSet<Sales_Order>();
            this.Quote_Items = new HashSet<Quote_Items>();
        }
    
        public int Quote_Number { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public System.DateTime Date_Required { get; set; }
        public System.DateTime Date_Requested { get; set; }
        public string Shipping_Address { get; set; }
        public int Customer { get; set; }
        public string Status { get; set; }
        public double Total_Value { get; set; }
        public int Sales_Person { get; set; }
        public string Shipping_City { get; set; }
        public string Shipping_State { get; set; }
        public Nullable<int> Shipping_Country_Id { get; set; }
        public string Shipping_ZipCode { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Sales_Person Sales_Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order> Sales_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_Items> Quote_Items { get; set; }
    }
}
