//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routing
    {
        public Nullable<decimal> Step_Number { get; set; }
        public Nullable<double> Setup_Time { get; set; }
        public Nullable<double> Quene_Time { get; set; }
        public Nullable<int> Capacity { get; set; }
        public int Work_Center_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Work_Center Work_Center { get; set; }
    }
}
