//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesModuleEntities : DbContext
    {
        public SalesModuleEntities()
            : base("name=SalesModuleEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AR_Invoice> AR_Invoice { get; set; }
        public virtual DbSet<Bin> Bins { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GL_Account> GL_Account { get; set; }
        public virtual DbSet<GL_Category> GL_Category { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Product_Class> Product_Class { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Quote_Items> Quote_Items { get; set; }
        public virtual DbSet<Routing> Routings { get; set; }
        public virtual DbSet<Sales_Order> Sales_Order { get; set; }
        public virtual DbSet<Sales_Person> Sales_Person { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<SO_Items> SO_Items { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Work_Calendar> Work_Calendar { get; set; }
        public virtual DbSet<Work_Center> Work_Center { get; set; }
    }
}
