//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Order()
        {
            this.AR_Invoice = new HashSet<AR_Invoice>();
            this.Shipments = new HashSet<Shipment>();
            this.SO_Items = new HashSet<SO_Items>();
        }
    
        public int SO_Number { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public System.DateTime Date_Required { get; set; }
        public System.DateTime Date_Requested { get; set; }
        public string Shipping_Address { get; set; }
        public int Customer { get; set; }
        public string Status { get; set; }
        public int PO_Number { get; set; }
        public Nullable<int> Tax { get; set; }
        public double Total_Value { get; set; }
        public int Sales_Person { get; set; }
        public Nullable<int> Quote_Number { get; set; }
        public string Shipping_City { get; set; }
        public string Shipping_State { get; set; }
        public Nullable<int> Shipping_Country_Id { get; set; }
        public string Shipping_ZipCode { get; set; }
        public int Shipped { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AR_Invoice> AR_Invoice { get; set; }
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Quote Quote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
        public virtual Sales_Person Sales_Person1 { get; set; }
        public virtual Tax Tax1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_Items> SO_Items { get; set; }
    }
}
