//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.AR_Invoice = new HashSet<AR_Invoice>();
        }
    
        public int Shipment_Number { get; set; }
        public int SO_Number { get; set; }
        public System.DateTime Date { get; set; }
        public int Customer { get; set; }
        public string Shipping_Address { get; set; }
        public string Tracking_Number { get; set; }
        public string Shipping_City { get; set; }
        public string Shipping_State { get; set; }
        public int Shipping_Country_Id { get; set; }
        public string Shipping_ZipCode { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public int Invoiced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AR_Invoice> AR_Invoice { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Sales_Order Sales_Order { get; set; }
    }
}
