//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApteanSalesFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Calendar
    {
        public string Name { get; set; }
        public Nullable<System.DateTime> Calendar { get; set; }
        public Nullable<int> No__of_Shifts { get; set; }
        public int Work_Center_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Work_Center Work_Center { get; set; }
    }
}
